apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sgek7v7co-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d41f73a8a2.6u7c.p3.openshiftapps.com/rhtap/rhtap-qe:7269084f9deeef704649a6a00c9b0cc0a206e8c8@sha256:fa0050dff8ee4ecb30a1a9e2622fd8170007864cba16dc8d5789696c6f4812c5
          name: container-image
